todo:
  keyword: "TODO"
  bodyKeyword: "BODY"
  blobLines: 5                # number|boolean, 0 or false to disable
  autoAssign: true            # string|string[]|boolean
  label: true                 # boolean|string|string[]
  reopenClosed: true          # boolean
